# Pull upstream changes from nixpak/nixpak daily at 12am UTC
name: Repo sync

on:
  schedule:
  - cron:  "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  repo-sync:
    name: Sync upstream changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/nixpak/nixpak"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
